export const ADD_TODO = "ADD_TODO"
export const REMOVE_TODO = "REMOVE_TODO"

//TODO TYPE
export const SET_TODO_DONE = "SET_TODO_DONE"
export const SET_TODO_PENDING = "SET_TODO_PENDING"

//TODO FILTER TYPE 
export const GET_DONE = "SET_DONE"
export const GET_PENDING = "SET_PENDING"

//MOOD TYPE
export const CHANGE_HAPPY = 'CHANGE_HAPPY'
export const CHANGE_MAD = 'CHANGE_MAD'
export const CHANGE_NORMAL = 'CHANGE_NORMAL'